import SubPageHeader from "@/components/landing/SubPageHeader";
import Footer from "@/components/landing/Footer";
import PageTransition from "@/components/PageTransition";
import {
  BookOpen,
  Rocket,
  Activity,
  Terminal,
  Network,
  Clock,
  ArrowRight,
  Copy,
  Check,
} from "lucide-react";
import { useState } from "react";

const SECTIONS = [
  { id: "intro", label: "Introduction" },
  { id: "quickstart", label: "Quick Start" },
  { id: "analysis", label: "Repository Analysis" },
  { id: "api", label: "API" },
  { id: "gitlawb", label: "Gitlawb Integration" },
];

export default function DocsPage() {
  return (
    <main data-testid="docs-page" className="relative min-h-screen bg-[#050505] text-white">
      <SubPageHeader active="docs" />
      <PageTransition>
        <DocsContent />
      </PageTransition>
      <Footer />
    </main>
  );
}

function DocsContent() {
  return (
    <section className="relative pt-32 sm:pt-40 pb-20">
      <div className="absolute inset-0 pointer-events-none grid-bg opacity-50 radial-fade" />
      <div className="relative mx-auto max-w-6xl px-5 sm:px-8 grid lg:grid-cols-[220px_1fr] gap-10">
        <aside className="hidden lg:block">
          <div className="sticky top-32">
            <div className="text-[11px] font-mono uppercase tracking-[0.18em] text-neutral-500 mb-4">
              On this page
            </div>
            <nav className="flex flex-col gap-1">
              {SECTIONS.map((s) => (
                <a
                  key={s.id}
                  href={`#${s.id}`}
                  className="text-sm text-neutral-400 hover:text-white px-2 py-1.5 rounded-md hover:bg-white/[0.04] transition"
                >
                  {s.label}
                </a>
              ))}
            </nav>
          </div>
        </aside>

        <article className="min-w-0">
          {/* Hero */}
          <div id="intro">
            <span className="inline-flex items-center gap-2 rounded-full gs-border bg-white/[0.03] px-3 py-1.5 text-xs text-neutral-300 font-mono">
              <BookOpen size={13} className="text-[#00E676]" /> documentation
            </span>
            <h1 className="font-display mt-5 text-4xl sm:text-5xl lg:text-6xl font-semibold tracking-tight text-white">
              GitSense Documentation
            </h1>
            <p className="mt-5 text-base sm:text-lg text-neutral-400 max-w-2xl leading-relaxed">
              GitSense is an AI-native repository intelligence platform. It analyses
              architecture, dependencies, contributors, security risks, and overall health
              of any repository — purpose-built for decentralized ecosystems like Gitlawb.
            </p>
            <p className="mt-3 text-sm text-neutral-500 max-w-2xl leading-relaxed">
              These docs are intentionally minimal during early access. They cover the
              fundamentals you need to scan your first repository and understand what
              GitSense returns.
            </p>
          </div>

          {/* Quick start */}
          <DocSection id="quickstart" icon={<Rocket size={14} className="text-[#00E676]" />} kicker="01" title="Quick Start">
            <p>
              Get your first analysis in under a minute. Open the live analyzer on the
              landing page, drop in any Gitlawb URL, and GitSense will return a full
              intelligence brief — no installation, no auth.
            </p>
            <ol className="mt-5 space-y-3 text-sm">
              {[
                "Open the GitSense landing page and scroll to the live analyzer.",
                "Paste a Gitlawb repository URL — e.g. gitlawb://gitsense/repository-demo.",
                "Press Analyze and watch the six-stage AI scan run end-to-end.",
                "Review repo health, dependencies, contributors, security risks, and AI recommendations.",
              ].map((step, i) => (
                <li key={i} className="flex gap-3">
                  <span className="font-mono text-[11px] text-[#00E676] mt-0.5">0{i + 1}</span>
                  <span className="text-neutral-300">{step}</span>
                </li>
              ))}
            </ol>

            <CodeBlock
              language="bash"
              code={`# coming soon
gitsense scan gitlawb://gitsense/repository-demo`}
            />
          </DocSection>

          {/* Repo analysis */}
          <DocSection id="analysis" icon={<Activity size={14} className="text-[#00C2FF]" />} kicker="02" title="Repository Analysis">
            <p>
              Every scan produces a structured report with five primary surfaces. Each
              surface is generated by a dedicated AI agent operating in parallel.
            </p>
            <div className="mt-5 grid sm:grid-cols-2 gap-3">
              {[
                { t: "Health score", d: "Composite 0–100 score weighing docs, tests, security, and ecosystem signals." },
                { t: "Architecture summary", d: "Natural-language overview of the codebase shape, module boundaries, and patterns." },
                { t: "Dependency graph", d: "Direct + transitive dependencies with risk tier and version drift." },
                { t: "Contributor insights", d: "Activity, ownership heatmaps, and bus factor across the repo." },
                { t: "Security risks", d: "CVE matches, secret detection, and config issues ranked by severity." },
                { t: "AI recommendations", d: "Concrete remediations and refactors prioritized by impact." },
              ].map((x) => (
                <div key={x.t} className="rounded-xl gs-border bg-[#0c0c0c] p-4">
                  <div className="text-sm font-medium text-white">{x.t}</div>
                  <p className="mt-1 text-sm text-neutral-400">{x.d}</p>
                </div>
              ))}
            </div>
          </DocSection>

          {/* API */}
          <DocSection id="api" icon={<Terminal size={14} className="text-[#00E676]" />} kicker="03" title="API">
            <p>
              A public REST API is in private preview. The endpoints below mirror the
              shape of the in-app analyzer and will be available with API keys at GA.
            </p>
            <CodeBlock
              language="http"
              code={`POST /api/analyze
Content-Type: application/json

{
  "repo_url": "gitlawb://gitsense/repository-demo"
}`}
            />
            <CodeBlock
              language="json"
              code={`{
  "repo_name": "gitsense/repository-demo",
  "health_score": 87,
  "files_analyzed": 1247,
  "dependencies": [...],
  "contributors": [...],
  "security_risks": [...],
  "ai_recommendations": [...]
}`}
            />
            <div className="mt-5 rounded-xl gs-border bg-[#0c0c0c] p-4 flex items-start gap-3">
              <Clock size={14} className="text-[#00C2FF] mt-1" />
              <p className="text-sm text-neutral-400">
                Authenticated API keys, webhooks, and SDKs (TypeScript, Python, Rust)
                are on the roadmap. Subscribe to release notes for availability.
              </p>
            </div>
          </DocSection>

          {/* Gitlawb integration */}
          <DocSection id="gitlawb" icon={<Network size={14} className="text-[#00C2FF]" />} kicker="04" title="Gitlawb Integration">
            <p>
              GitSense was built natively for decentralized repositories. The Gitlawb
              integration lets you paste any <span className="font-mono text-neutral-300">gitlawb://</span>{" "}
              URL and receive a complete intelligence brief — no host accounts, no
              centralized indexes.
            </p>
            <div className="mt-5 grid sm:grid-cols-2 gap-3">
              <Callout
                title="Native URL support"
                body="Drop a gitlawb:// URL anywhere in GitSense — the live analyzer, API, or CLI (soon)."
              />
              <Callout
                title="Decentralized-first"
                body="No proprietary metadata required. GitSense reads what the Gitlawb network exposes."
              />
            </div>
          </DocSection>

          {/* Soon */}
          <div className="mt-16 rounded-2xl gs-border bg-[#0a0a0a] p-6 sm:p-7 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <div className="text-[11px] font-mono text-[#00E676] uppercase tracking-[0.15em]">
                In progress
              </div>
              <div className="mt-1 font-display text-lg font-semibold text-white">
                More documentation coming soon
              </div>
              <p className="mt-1 text-sm text-neutral-400 max-w-xl">
                CLI reference, SDK guides, webhook recipes, and self-hosting documentation
                will land progressively. The shape of these docs may change before GA.
              </p>
            </div>
            <a
              href="/#analyzer"
              data-testid="docs-try-analyzer"
              className="inline-flex items-center gap-2 rounded-xl bg-[#00E676] text-black px-5 py-3 text-sm font-medium hover:bg-[#00d169] active:scale-[0.98] transition"
            >
              Try the analyzer
              <ArrowRight size={15} />
            </a>
          </div>
        </article>
      </div>
    </section>
  );
}

function DocSection({ id, icon, kicker, title, children }) {
  return (
    <section id={id} className="mt-16 scroll-mt-32">
      <div className="flex items-center gap-2 mb-2">
        <span className="inline-flex h-7 w-7 items-center justify-center rounded-lg gs-border bg-black">
          {icon}
        </span>
        <span className="font-mono text-[11px] text-neutral-500">{kicker}</span>
      </div>
      <h2 className="font-display text-2xl sm:text-3xl font-semibold text-white tracking-tight">
        {title}
      </h2>
      <div className="mt-4 text-neutral-400 text-[15px] leading-relaxed max-w-2xl">
        {children}
      </div>
    </section>
  );
}

function Callout({ title, body }) {
  return (
    <div className="rounded-xl gs-border bg-[#0c0c0c] p-4">
      <div className="text-sm font-medium text-white">{title}</div>
      <p className="mt-1 text-sm text-neutral-400">{body}</p>
    </div>
  );
}

function CodeBlock({ language, code }) {
  const [copied, setCopied] = useState(false);
  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1400);
    } catch {}
  };

  return (
    <div className="relative mt-5 rounded-xl gs-border bg-[#0a0a0a] overflow-hidden group">
      <div className="flex items-center justify-between border-b border-white/[0.06] px-4 py-2">
        <span className="text-[10px] font-mono uppercase tracking-[0.15em] text-neutral-500">
          {language}
        </span>
        <button
          onClick={onCopy}
          className="inline-flex items-center gap-1.5 text-[11px] font-mono text-neutral-400 hover:text-white transition"
        >
          {copied ? <Check size={12} className="text-[#00E676]" /> : <Copy size={12} />}
          {copied ? "copied" : "copy"}
        </button>
      </div>
      <pre className="px-4 py-4 text-[13px] font-mono text-neutral-200 whitespace-pre-wrap break-words">
        {code}
      </pre>
    </div>
  );
}
